name: restlib_example
description: Sample applications using the restlib framework.
dependencies:
  logging: any
  path: any
  restlib_common:
    git: https://code.google.com/p/dart-restlib.common/
  restlib_core:
    git: https://code.google.com/p/dart-restlib.core/  
  restlib_http_connector:
    git: https://code.google.com/p/dart-restlib.http-connector/
  restlib_server:
    git: https://code.google.com/p/dart-restlib.server/
